# Generated by Django 4.2.9 on 2024-01-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('in_columbus', models.IntegerField()),
                ('previous_grader', models.IntegerField()),
                ('previous_classes', models.TextField(blank=True)),
            ],
        ),
    ]
