# Generated by Django 4.2.9 on 2024-02-12 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OSU_CSE_GMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnassignedStudent',
            fields=[
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='OSU_CSE_GMS.student')),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
