# Generated by Django 4.2.10 on 2024-02-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OSU_CSE_GMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
