# Generated by Django 4.2.9 on 2024-02-20 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OSU_CSE_GMS', '0002_alter_course_name'),
        ('OSU_CSE_GMS', '0002_unassignedstudent'),
    ]

    operations = [
    ]
