# Generated by Django 4.2.9 on 2024-01-31 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OSU_CSE_GMS', '0002_administrator_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=30)),
                ('instruction_mode', models.CharField(choices=[('SYNCHRNONOUS', 'SYNCHRNONOUS'), ('ASYNCHRNONOUS', 'ASYNCHRNONOUS')], max_length=13)),
                ('semester', models.CharField(max_length=6)),
                ('time', models.CharField(blank=True, max_length=30)),
                ('days_of_week', models.CharField(blank=True, max_length=30)),
                ('classroom', models.CharField(blank=True, max_length=30)),
                ('course_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OSU_CSE_GMS.course')),
                ('instructor', models.ForeignKey(default='No Instructor', on_delete=django.db.models.deletion.SET_DEFAULT, to='OSU_CSE_GMS.instructor')),
            ],
            options={
                'unique_together': {('course_number', 'section_number')},
            },
        ),
    ]
