# Generated by Django 4.2.9 on 2024-02-27 00:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OSU_CSE_GMS', '0003_merge_0002_alter_course_name_0002_unassignedstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='previous_classes',
        ),
        migrations.AddField(
            model_name='student',
            name='graded_last_term',
            field=models.CharField(default=None, max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course_number', 'section_number', 'semester')},
        ),
        migrations.CreateModel(
            name='PreviousClassTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.CharField(blank=True, max_length=40)),
                ('pref_num', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('course_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OSU_CSE_GMS.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OSU_CSE_GMS.student')),
            ],
            options={
                'unique_together': {('student_id', 'course_number')},
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], max_length=8)),
                ('section_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OSU_CSE_GMS.section')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OSU_CSE_GMS.student')),
            ],
            options={
                'unique_together': {('student_id', 'section_number')},
            },
        ),
    ]
