# Generated by Django 4.2.9 on 2024-02-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OSU_CSE_GMS', '0004_remove_student_previous_classes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='in_columbus',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='previous_grader',
            field=models.IntegerField(null=True),
        ),
    ]
