# Generated by Django 4.2.9 on 2024-02-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OSU_CSE_GMS', '0005_alter_student_in_columbus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='graded_last_term',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
