# Generated by Django 4.2.9 on 2024-02-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OSU_CSE_GMS', '0006_alter_student_graded_last_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='num_graders_needed',
            field=models.IntegerField(default=1),
        ),
    ]
