# Generated by Django 4.2.9 on 2024-03-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OSU_CSE_GMS', '0007_section_num_graders_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
