# Generated by Django 4.2.10 on 2024-02-29 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OSU_CSE_GMS', '0007_alter_section_instructor'),
        ('OSU_CSE_GMS', '0007_section_num_graders_needed'),
    ]

    operations = [
    ]
