# Generated by Django 4.2.10 on 2024-03-02 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OSU_CSE_GMS', '0008_alter_administrator_id_alter_instructor_id_and_more'),
        ('OSU_CSE_GMS', '0008_merge_20240228_2111'),
    ]

    operations = [
    ]
