# Generated by Django 4.2.9 on 2024-03-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OSU_CSE_GMS', '0009_merge_20240302_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='instruction_mode',
            field=models.CharField(choices=[('SYNCHRONOUS', 'SYNCHRONOUS'), ('ASYNCHRONOUS', 'ASYNCHRONOUS')], max_length=13),
        ),
    ]
